name: invert string
on:
  push:
    branches:
      - main 
  
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.0.4
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          # pip install -e .
      - name: Test with pytest
        run: python -m pytest